# Builds a JSON file from the main.json bicep

name: BicepBuild

on:
  push:
    branches:
     - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
      YOUTUBEFILE: youtube-AS15169.txt
      YOUTUBEFILETEMP: youtube-AS15169-temp.txt

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUBYOUTUBEIPS }}

      - name: Generate IP List
        shell: bash
        run: |
          sudo apt update
          sudo apt install whois -y
          whois -h whois.radb.net -- '-i origin AS15169' | grep ^route | sed -e 's/route://g' -e 's/route6://g' -e 's/ //g' > "${{ env.YOUTUBEFILETEMP }}"
          ls -la
          file1="${{ env.YOUTUBEFILE }}"
          file2="${{ env.YOUTUBEFILETEMP }}"
          if cmp -s "$file1" "$file2"; then
              printf 'The file "%s" is the same as "%s"\n' "$file1" "$file2"
              printf 'Exiting without commiting changes\n'
          else
              printf 'The file "%s" is different from "%s"\n' "$file1" "$file2"
              cp $file2 $file1
              rm $file2
              git config --global user.email "username@users.noreply.github.com"
              git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
              git add *
              git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
              git push
              cat "${{ env.YOUTUBEFILE }}"
          fi


      # - name: GIT Push youtube-AS15169.txt file
      #   uses: actions-x/commit@v6
      #   with:
      #     message: Adding auto compiled youtube-AS15169.txt