# Builds a JSON file from the main.json bicep

name: BicepBuild

on:
  push:
    branches:
     - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate IP List
        shell: bash
        run: |
          sudo apt update
          sudo apt install whois -y
          whois -h whois.radb.net -- '-i origin AS15169' | grep ^route | sed -e 's/route://g' -e 's/route6://g' -e 's/ //g' > youtube-AS15169-test.txt
          ls -la
          cat youtube-AS15169-test.txt

      - name: GIT Push youtube-AS15169.txt file
        uses: actions-x/commit@v6
        with:
          message: Adding auto compiled youtube-AS15169.txt