# Builds a JSON file from the main.json bicep

name: BicepBuild

on:
  push:
    branches:
     - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
      YOUTUBEFILE: youtube-AS15169.txt

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUBYOUTUBEIPS }}

      - name: Generate IP List
        shell: bash
        run: |
          sudo apt update
          sudo apt install whois -y
          whois -h whois.radb.net -- '-i origin AS15169' | grep ^route | sed -e 's/route://g' -e 's/route6://g' -e 's/ //g' > "${{ env.YOUTUBEFILE }}"
          ls -la
          git status
          git config --global user.email "username@users.noreply.github.com"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git add *
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git status
          git push
          cat "${{ env.YOUTUBEFILE }}"
          git status


      # - name: GIT Push youtube-AS15169.txt file
      #   uses: actions-x/commit@v6
      #   with:
      #     message: Adding auto compiled youtube-AS15169.txt